// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: akQUwPYY2eStENCEGYmmQw
// Component: j7fyymFTtU
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import RecentListing from "../../RecentListing"; // plasmic-import: w1_vCJeiHk/component

import { useScreenVariants as useScreenVariantshKdOjWx6MiWhf } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: HKdOJWx6MIWhf/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: akQUwPYY2eStENCEGYmmQw/projectcss
import sty from "./PlasmicRecentListingsBlock.module.css"; // plasmic-import: j7fyymFTtU/css

export type PlasmicRecentListingsBlock__VariantMembers = {};

export type PlasmicRecentListingsBlock__VariantsArgs = {};
type VariantPropType = keyof PlasmicRecentListingsBlock__VariantsArgs;
export const PlasmicRecentListingsBlock__VariantProps =
  new Array<VariantPropType>();

export type PlasmicRecentListingsBlock__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRecentListingsBlock__ArgsType;
export const PlasmicRecentListingsBlock__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicRecentListingsBlock__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultRecentListingsBlockProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicRecentListingsBlock__RenderFunc(props: {
  variants: PlasmicRecentListingsBlock__VariantsArgs;
  args: PlasmicRecentListingsBlock__ArgsType;
  overrides: PlasmicRecentListingsBlock__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantshKdOjWx6MiWhf()
  });

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <RecentListing
            className={classNames("__wab_instance", sty.recentListing__kYcOc)}
          />
        ),

        value: args.children
      })}
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRecentListingsBlock__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRecentListingsBlock__VariantsArgs;
    args?: PlasmicRecentListingsBlock__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRecentListingsBlock__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRecentListingsBlock__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRecentListingsBlock__ArgProps,
      internalVariantPropNames: PlasmicRecentListingsBlock__VariantProps
    });

    return PlasmicRecentListingsBlock__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRecentListingsBlock";
  } else {
    func.displayName = `PlasmicRecentListingsBlock.${nodeName}`;
  }
  return func;
}

export const PlasmicRecentListingsBlock = Object.assign(
  // Top-level PlasmicRecentListingsBlock renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicRecentListingsBlock
    internalVariantProps: PlasmicRecentListingsBlock__VariantProps,
    internalArgProps: PlasmicRecentListingsBlock__ArgProps
  }
);

export default PlasmicRecentListingsBlock;
/* prettier-ignore-end */
